STI Prediction with ANN
========================================================
Intro
--------
The steps we follow will be the same as the SimpleProcedure using the sqrt. We hope to train the Neural Network according to a suitable test set in order to predict the rest of the data. Once we have trained our NN, we will do a prediction to determine the accuracy.

### Data prep 
```{r}
#Install neuralnet if not already installed
install.packages("neuralnet")
library('neuralnet')

stidata <- read.csv("STI 2004-2013_030214.csv")

# Prepare the training data
# We take a set of 50 first to train the NN
traindata <- stidata[, c("Close", "Tmr.Close")]

#Close is the input and Tmr.Close is the expected output
```

### Now we train the NN 
```{r}
# Several NN needs to be generated to get a good one
stipredictor <- neuralnet(Tmr.Close ~ Close, traindata, hidden = 10, threshold = 0.01, lifesign = 'full')
print(stipredictor)
plot(stipredictor)
```

### Training complete, now we test the data
```{r}
# Create the data set from row 51 to the end
sticlose <- as.data.frame(stidata[, c("Close")])

# Compute the data
computed <- compute(stipredictor, sticlose)

print(computed$net.result)
overview <- cbind(sticlose, computed$net.result)
print(overview)

##Edit - works with the following data normalization process.

#Standardizing data before feeding into the neural net is almost a pre-req. For values much greater than 1, the change in values is not represented by appropriate change in the activation function typically of the nature tanh. 
newdata<-stidata[,c("Open","High","Low","Close","Volume","Target_Close")]
stdev_newdata<-apply(newdata,2,sd,na.rm=TRUE)
Means_newdata<-apply(newdata,2,mean,na.rm=TRUE)
scale_newdata<-scale(newdata)
train_newdata<-newdata[1:2000,]
test_newdata<-scale_newdata[2001:2527,]
test_newdata<-test_newdata[ ,-6]
new_predictor <- neuralnet(Target_Close ~ Open+High+Low+Close+Volume, train_newdata, hidden = 10, threshold = 0.01, lifesign = 'full')
new_computed<-compute(new_predictor,test_newdata)
0.8751611739070*stdev_newdata[6]+Means_newdata[6] #to predict the value of the last closing day value.

```
